module.exports = {
    dilmahCountries : [
        {
            label:'Global',
            value:'GLOBAL',
            flag:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJXVsHmz-7tvfflfdoy1VgyaUnrLov6Yq50Q&usqp=CAU'
        },
        {
            label:'Australia',
            value:'AU',
            flag:'https://www.worldometers.info/img/flags/small/tn_as-flag.gif'
        },
        {
            label:'Netherland',
            value:'NL',
            flag:'https://www.worldometers.info/img/flags/small/tn_nl-flag.gif'
        },
        {
            label:'Singapore',
            value:'SG',
            flag:'https://www.worldometers.info/img/flags/small/tn_sn-flag.gif'
        },
        {
            label:'United Kingdom',
            value:'GB',
            flag:'https://www.worldometers.info/img/flags/small/tn_uk-flag.gif'
        },
        {
            label:'Ukraine',
            value:'UA',
            flag:'https://www.worldometers.info/img/flags/small/tn_up-flag.gif'
        },
        {
            label:'Moldova',
            value:'MD',
            flag:'https://www.worldometers.info/img/flags/small/tn_md-flag.gif'
        },
        {
            label:'Russia',
            value:'RU',
            flag:'https://www.worldometers.info/img/flags/small/tn_rs-flag.gif'
        },
        {
            label:'Lituania',
            value:'LT',
            flag:'https://www.worldometers.info/img/flags/small/tn_lh-flag.gif'
        },
        {
            label:'New Zealand',
            value:'NZ',
            flag:'https://www.worldometers.info/img/flags/small/tn_nz-flag.gif'
        },
        {
            label:'Hungary',
            value:'HU',
            flag:'https://www.worldometers.info/img/flags/small/tn_hu-flag.gif'
        },
        {
            label:'China',
            value:'CN',
            flag:'https://www.worldometers.info/img/flags/small/tn_ch-flag.gif'
        },
        {
            label:'South Africa',
            value:'ZA',
            flag:'https://www.worldometers.info/img/flags/small/tn_sf-flag.gif'
        },
        {
            label:'Thailand',
            value:'TH',
            flag:'https://www.worldometers.info/img/flags/small/tn_th-flag.gif'
        },
        {
            label:'Sweden',
            value:'SE',
            flag:'https://www.worldometers.info/img/flags/small/tn_sw-flag.gif'
        },
        {
            label:'Canada',
            value:'CA',
            flag:'https://www.worldometers.info/img/flags/small/tn_ca-flag.gif'
        },
        {
            label:'USA',
            value:'US',
            flag:'https://www.worldometers.info/img/flags/small/tn_us-flag.gif'
        },
        {
            label:'France',
            value:'FR',
            flag:'https://www.worldometers.info/img/flags/small/tn_fr-flag.gif'
        },
        {
            label:'MENA',
            value:'SA',
            flag:'https://www.worldometers.info/img/flags/small/tn_sa-flag.gif'
        }
    ] 
}